"""Package: agent_runtime_pkg"""
from src.agent_runtime_pkg._agent_runtime_pkg_merged import _message_ts, _classify_failure_domain, _is_tool_error_payload, _detect_failure_streak
from src.agent_runtime_pkg._agent_runtime_pkg_merged import _consecutive_error_tail_count, _last_consecutive_error_block, _format_tool_error_streak_nudge, format_tool_segment_summary, registry_to_openai_tools
from src.agent_runtime_pkg._agent_runtime_pkg_merged import _strip_think_markup, _is_bare_chain_of_thought, scrub_bare_cot_from_assistant_text
from src.agent_runtime_pkg._agent_runtime_pkg_merged import build_api_projection_messages, merge_llm_tail_into_full, trim_messages_by_user_rounds, strip_compact_block_from_system, _context_compact_enabled, _messages_body_json_bytes, _format_transcript_for_summary, _summarizer_llm
from src.agent_runtime_pkg._agent_runtime_pkg_merged import default_system_prompt
from src.agent_runtime_pkg._agent_runtime_pkg_merged import maybe_compact_context_messages, _truncate_tool_output
from src.agent_runtime_pkg._agent_runtime_pkg_merged import run_llm_tool_loop
from src.agent_runtime_pkg._agent_runtime_pkg_merged import strip_inline_tool_markup_from_assistant_text, parse_inline_qwen_tool_calls, parse_inline_json_tool_calls, _strip_json_fences_once_each, _inline_tool_parse_enabled, _allowed_tool_names_for_loop
